### PR TITLE
Added Broadcast & steal

### PR DESCRIPTION
**Pull request by bilal-08**

### CODE REVIEW

**Review by Oreki-san — CHANGES_REQUESTED** [review]
It would be great if we can bc with a pic or gif but it doesn't support that

**Comment by ShinNouzen** [comment]
@bilal-08 please change the category to 'dev' and usage to 'bc' from 'everyone'.

**Comment by bilal-08** [comment]
> It would be great if we can bc with a pic or gif but it doesn't support that

im thinking of adding forward msg welp i'll look into it

**Review by Nisarga-Developer — APPROVED** [review]
Cool. 

Awesome PR

**Comment by Nisarga-Developer** [comment]
Well

**Pull request closed without merging**
