### PR TITLE
Update EventHandler.ts

### PR DESCRIPTION
**Pull request by Raj6544**
A little bit change

### CODE REVIEW

**Comment by PrajjwalDatir** [comment]
I believe that saying the person has left the chat is better.
`we will miss you` is dependent on situation.

What do you think? @Raj6544

**Comment by Raj6544** [comment]
Ok then just Bye message ...
It will be right?? @PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
Why are you trying to change the original? @Raj6544

**Comment by Raj6544** [comment]
Ummm, if anyone left the gc then user already can see user lefting chat. That's why I was trying to replace by 'Bye'. It can can be annoying for if anyone left chat that already can see but again if it repeating user left chat then it could be annoying in my views.

**Comment by PrajjwalDatir** [comment]
>  if anyone left the gc then user already can see user lefting chat
- we see the number as leaving ( unless we've saved the number )
- Sometimes Bot might respond late, so we might not get the 'bye' message as soon as user has left.
- I'm ok with the `user left the chat. Bye 👋` part. But I think that's an unnecessary change.

Closing PR.

**Pull request closed without merging**
