### PR TITLE
create biodata command for generating biodata UwU

### PR DESCRIPTION
**Pull request by Nisarga-Developer**

### CODE REVIEW

**Comment by Nisarga-Developer** [comment]
@PrajjwalDatir ??

**Comment by PrajjwalDatir** [comment]
If passed without country code return list of valid country codes, which will be fetched from https://api.abirhasan.wtf/bioDataGenerator

**Comment by Nisarga-Developer** [comment]
I don't have the list of valid country codes, neither does the API
documentation has.

**Comment by PrajjwalDatir** [comment]
@Nisarga-Developer

**Comment by Nisarga-Developer** [comment]
> @Nisarga-Developer

Dude, busy with exams and stuff. Will try changing the API soon :)

**Comment by Nisarga-Developer** [comment]
;)

**Pull request closed without merging**
