### PR TITLE
Created ip.ts for info about ip address

### PR DESCRIPTION
**Pull request by Nisarga-Developer**

### CODE REVIEW

**Comment by Nisarga-Developer** [comment]
@PrajjwalDatir 
Merge this?

**Comment by PrajjwalDatir** [comment]
@Nisarga-Developer Check for undefined response.

**Comment by Nisarga-Developer** [comment]
> @Nisarga-Developer Check for undefined response.

Dude, busy with exams and stuff. Will try changing the API soon :)

**Comment by Nisarga-Developer** [comment]
Sad

> Stale pull request message

@PrajjwalDatir Merge this :)

**Comment by Nisarga-Developer** [comment]
Praaaaajwaaaal!

**Comment by Nisarga-Developer** [comment]
`
wp8346265
`

Now merge this dude

**Pull request merged**
